version: "3.11"
   
services:
  app:
    build: .
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"